name: Generate Snake Animation

on:
  # Run automatically every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  
  push:
    branches: [ main ]
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  generate:

        uses: Platane/snk@v3
        with:
          github_user_name: Rjj18
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark