name: Generate Snake Animation

on:
  # Run automatically every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  
  # Run on every push to main
  push:
    branches: [ main ]
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
      
      # Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Rjj18
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark
      
      # Commit and push the generated files
      - name: Push generated files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg
          git diff --staged --quiet || git commit -m "Update snake animation"
          git push
